---
######################################################################
#
# Mark Higginbottom / Jon Spriggs
#
# 05/12/2016 - 13/03/2018
#
# Playbook to configure a centos7 vm with AWX
#
#
######################################################################
- name: AWX control machine
  hosts: "{{ servers }}"
  become: Yes
  become_user: root

  vars:
    nodejs_version: "6.x"
    pip_install_packages:
      - name: docker-py

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - name: geerlingguy.repo-epel
      when: ansible_os_family == "RedHat"
    - geerlingguy.git
    - geerlingguy.ansible
    - geerlingguy.docker
    - geerlingguy.pip
    - geerlingguy.nodejs
    - ansible-role-awx  
    - jontheniceguy.simple-nginx-tls-reverse-proxy

# Copy certificates from shared certificate directory to ~/.ssh directory
# This is the correct place for them and also because windows permissions messes
# up the SHARED file permissions so that the certificates are refused.
# NOTE: use shell module as command cannot do wildcards i.e. *
#
# This part has been commented out, as I can't see why there's a requirement to add
# PEM files to the outer .ssh directory - these aren't accessible to the docker
# container that is running AWX :(
#
#  tasks:
#      - name: directory
#        command: pwd
#        register: dir_out
#      - name: Copy certificates to /home/vagrant/.ssh
#        shell: cp -fuv /home/vagrant/shared/certificates/*.pem /home/vagrant/.ssh
#        args:
#          chdir: /vagrant
#        register: move_result
#      - name: Own certificates
#        shell: chown vagrant:vagrant /home/vagrant/.ssh/*.pem
#      - name: Set permissions on certificates /home/vagrant/.ssh
#        shell: chmod 600 /home/vagrant/.ssh/*.pem
#      - name: Copy motd
#        shell: cp -fuv /home/vagrant/shared/ansible/files/motd.sh /etc/profile.d
#      - name: Set permissions on DB files
#        shell: /vagrant/shared/util/restore_awx_db.sh
#################
# DEBUG PATTERN #
#################
#      - name: directory
#        command: pwd
#        register: dir_out
#      - debug: msg="{{ dir_out.stdout }}"
#      - debug: msg="{{ dir_out.stderr }}"
