---
- name: Ensure postgres_data_dir exists
  file:
    state: directory
    path: "{{ postgres_data_dir }}"
- name: directory
  command: ls -al {{ postgres_data_dir }}
  register: dir_out
- debug: msg="{{ dir_out.stdout }}"
- debug: msg="{{ dir_out.stderr }}"

- name: Run the AWX installation playbook.
  command: "ansible-playbook -i inventory install.yml -e postgres_data_dir={{ postgres_data_dir }}"
  args:
    chdir: "{{ awx_repo_dir }}/installer"
    creates: /etc/awx_playbook_complete

- name: Create a file to mark whether this playbook has completed.
  file:
    path: /etc/awx_playbook_complete
    state: touch
  changed_when: False
#################
# DEBUG PATTERN #
#################
#      - name: directory
#        command: pwd
#        register: dir_out
#      - debug: msg="{{ dir_out.stdout }}"
#      - debug: msg="{{ dir_out.stderr }}"