---
- name: Ensure postgres_data_dir exists
  file:
    state: directory
    path: "{{ postgres_data_dir }}"
  when: postgres_data_dir is defined

- name: Ensure project_data_dir exists
  file:
    state: directory
    path: "{{ project_data_dir }}"
  when: project_data_dir is defined

# Variables defined by https://github.com/ansible/awx/blob/1.0.4/installer/local_docker/tasks/standalone.yml#L76-L108
- name: Run the AWX installation playbook.
  command: >
    ansible-playbook -i inventory install.yml -e "
    {% if postgres_data_dir is defined %}postgres_data_dir={{ postgres_data_dir }}{% endif %}
    {% if project_data_dir is defined %}project_data_dir={{ project_data_dir }}{% endif %}
    {% if admin_user is defined %}default_admin_user={{ admin_user }}{% endif %}
    default_admin_password={{ admin_password }}"
  args:
    chdir: "{{ awx_repo_dir }}/installer"
    creates: /etc/awx_playbook_complete

- name: Create a file to mark whether this playbook has completed.
  file:
    path: /etc/awx_playbook_complete
    state: touch
  changed_when: False
